### ISSUE TITLE
Falta la clase com.silmood.topyork.Injection

### ISSUE THREAD

**Issue by ecamacho** [silmood/Top-York#2]
En master y en el branch 2-MVP la app no compila porque no encuentra la clase com.silmood.topyork.Injection

**Comment by silmood** [comment]
Intentaste cambiar el product flavor `prod` ?

![screenshot at feb 26 13-56-00](https://cloud.githubusercontent.com/assets/7158683/13363763/ca2cc85a-dc90-11e5-8aa9-271e2980b3e7.png)

**Comment by ecamacho** [comment]
Excelente, era eso . Gracias
